version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
archives:
  - name_template: >-
      {{ .ProjectName }}_{{- .Tag }}_{{- if eq .Os "darwin" }}macOS{{- else }}{{ .Os }}{{ end }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: gitmux
    homepage: "https://github.com/arl/gitmux"
    description: "Git in your tmux status bar."
    license: "MIT"
    url_template: "https://github.com/arl/gitmux/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    skip_upload: false
    repository:
      owner: arl
      name: homebrew-arl
      branch: main
    commit_author:
      name: goreleaser-bot
      email: bot@goreleaser.com
