before:
  hooks:
    - go mod tidy
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
archives:
- replacements:
    darwin: macOS
    linux: linux
    386: x86
    amd64: amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
