name: Continuous Deployment

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    name: Publish release to github/brew
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.x"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  check_brew:
    name: Check brew tap has been updated
    runs-on: macos-latest
    needs: goreleaser
    steps:
      - name: brew tap/install
        run: |
          brew tap arl/arl
          brew install gitmux
          gitmux -V
      - name: check gitmux version
        run: |
          [ v$(gitmux -V) == "$GITHUB_REF_NAME" ]
