on: [push, pull_request]
name: Continuous Integration
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.x"
      - name: Tests
        run: go test -race ./...

  goreleaser:
    name: Publish releases to github and brew tap
    needs: tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.x"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  check_brew:
    name: Check brew tap has been updated
    needs: goreleaser
    runs-on: macos-latest
    steps:
      - name: Install gitmux with brew
        run: |
          brew tap arl/arl
          brew install gitmux
          gitmux -V
      - name: Check installed gitmux version
        run: |
          [ v$(gitmux -V) == "$GITHUB_REF_NAME" ]
